# Setup
title: ğ™°ğš•ğšğš¡ ğ™¶. ğš†ğšŠğš—ğš, ğ—”ğ—¹ğ—²ğ˜… ğ—š. ğ—ªğ—®ğ—»ğ—´
description: ğŸ‡¸â€ŒğŸ‡¨â€ŒğŸ‡®â€ŒğŸ‡ªâ€ŒğŸ‡³â€ŒğŸ‡¨â€ŒğŸ‡ªâ€Œ ğŸ‡ªâ€ŒğŸ‡³â€ŒğŸ‡¹â€ŒğŸ‡­â€ŒğŸ‡ºâ€ŒğŸ‡¸â€ŒğŸ‡®â€ŒğŸ‡¦â€ŒğŸ‡¸â€ŒğŸ‡¹â€Œ
url: https://github.com/al2wang/
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: al2wang
  card: summary
logo: logo.png
social:
  name: al2_gyy_w
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Guangyuan Wang
  url: https://github.com/al2wang/
  email: lightever131@gmail.com
